### sign-up-controller - customer
POST http://localhost:8085/signup/customer
Content-Type: application/json

{
  "name": "suh-customer",
  "email": "chan4760@naver.com",
  "password": "string",
  "phone": "string",
  "birth": "2023-12-29"
}


### sign-up-controller - partner
POST http://localhost:8085/signup/partner
Content-Type: application/json

{
  "name": "suh-partner",
  "email": "chan4760@gmail.com",
  "password": "string",
  "phone": "string",
  "birth": "2023-12-29"
}


######################################################
/

### sign-in-controller - customer
POST http://localhost:8085/signin/customer
Content-Type: application/json

{
  "email": "chan4760@naver.com",
  "password": "string"
}

### eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJDVVNUT01FUiIsImlhdCI6MTcwNDEzNDQ2OCwiZXhwIjoxNzA0MjIwODY4fQ.NF_2GYyt0bxFrGWIa-56FFnGIV1MFOuZaHSheNl_3lM

### sign-in-controller - partner
POST http://localhost:8085/signin/partner
Content-Type: application/json

{
  "email": "chan4760@gmail.com",
  "password": "string"
}

###eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTM0NDgxLCJleHAiOjE3MDQyMjA4ODF9.Soshn293kO5bYugB-D8TLTua2XDYTzdTADWTFXfGhA4

######################################################
/

### store-contorller -/store/partner/edit/{storeId}
PUT http://localhost:8085/store/partner/edit/1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTM0NDgxLCJleHAiOjE3MDQyMjA4ODF9.Soshn293kO5bYugB-D8TLTua2XDYTzdTADWTFXfGhA4

{
  "name": "Store1",
  "location": "string",
  "description": "string",
  "openingTime": "01:00:00",
  "closingTime": "23:50:00",
  "isAvaliableReservation": true,
  "maxReservationPeople": 4
}

### store-contorller -/store/partner/create
POST http://localhost:8085/store/partner/create
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTM0NDgxLCJleHAiOjE3MDQyMjA4ODF9.Soshn293kO5bYugB-D8TLTua2XDYTzdTADWTFXfGhA4

{
  "name": "Store1",
  "location": "string",
  "description": "string",
  "openingTime": "00:01:00",
  "closingTime": "23:50:00",
  "isAvaliableReservation": true,
  "maxReservationPeople": 4
}



### store-contorller -/store/search
GET http://localhost:8085/store/search?keyWord=Store
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTM0NDgxLCJleHAiOjE3MDQyMjA4ODF9.Soshn293kO5bYugB-D8TLTua2XDYTzdTADWTFXfGhA4

### store-contorller -/store/partner/stores-info
GET http://localhost:8085/store/partner/stores-info
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTM0NDgxLCJleHAiOjE3MDQyMjA4ODF9.Soshn293kO5bYugB-D8TLTua2XDYTzdTADWTFXfGhA4

### store-contorller -/store/partner/delete/{storeId}
DELETE http://localhost:8085/store/partner/delete/2
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTM0NDgxLCJleHAiOjE3MDQyMjA4ODF9.Soshn293kO5bYugB-D8TLTua2XDYTzdTADWTFXfGhA4

######################################################
/

### reservation-controller - /reservation/customer/create
POST http://localhost:8085/reservation/customer/create
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJDVVNUT01FUiIsImlhdCI6MTcwNDEzNDQ2OCwiZXhwIjoxNzA0MjIwODY4fQ.NF_2GYyt0bxFrGWIa-56FFnGIV1MFOuZaHSheNl_3lM

{
  "storeName": "Store1",
  "reservationName": "chan",
  "reservationPhone": "000110243r0",
  "reservationTime": "2024-01-02T21:20:00",
  "numberOfPerson": 3
}

### reservation-controller - /reservation/partner/store-reservation-info/{storeId}
GET http://localhost:8085/reservation/partner/store-reservation-info/1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTM0NDgxLCJleHAiOjE3MDQyMjA4ODF9.Soshn293kO5bYugB-D8TLTua2XDYTzdTADWTFXfGhA4

### reservation-controller - /reservation/customer/reservations-info
GET http://localhost:8085/reservation/customer/reservations-info
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJDVVNUT01FUiIsImlhdCI6MTcwNDEzNDQ2OCwiZXhwIjoxNzA0MjIwODY4fQ.NF_2GYyt0bxFrGWIa-56FFnGIV1MFOuZaHSheNl_3lM

### reservation-controller - /reservation/kiosk/visit-confirm/{reservationCode}
POST http://localhost:8085/reservation/kiosk/visit-confirm/fb48f9f8cdcc48109af7195da62bcada

### reservation-controller - /reservation/partner/confirm/{reservationId}
POST http://localhost:8085/reservation/partner/confirm/3
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTM0NDgxLCJleHAiOjE3MDQyMjA4ODF9.Soshn293kO5bYugB-D8TLTua2XDYTzdTADWTFXfGhA4

### reservation-controller -/reservation/customer/cancel/{reservationId}
POST http://localhost:8085/reservation/customer/cancel/1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJDVVNUT01FUiIsImlhdCI6MTcwNDEzNDQ2OCwiZXhwIjoxNzA0MjIwODY4fQ.NF_2GYyt0bxFrGWIa-56FFnGIV1MFOuZaHSheNl_3lM


### reservation-controller - /reservation/customer/edit/{reservationId}
PUT http://localhost:8085/reservation/customer/edit/1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJDVVNUT01FUiIsImlhdCI6MTcwNDEzNDQ2OCwiZXhwIjoxNzA0MjIwODY4fQ.NF_2GYyt0bxFrGWIa-56FFnGIV1MFOuZaHSheNl_3lM

{
  "reservationName": "editedSuhSaechan",
  "reservationPhone": "010345654",
  "reservationTime": "2024-01-05T18:46:30.480Z",
  "numberOfPerson": 3
}

################################################
/리뷰작성

### review-controller - /review/create
POST http://localhost:8085/review/create
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJDVVNUT01FUiIsImlhdCI6MTcwNDEzNDQ2OCwiZXhwIjoxNzA0MjIwODY4fQ.NF_2GYyt0bxFrGWIa-56FFnGIV1MFOuZaHSheNl_3lM

{
  "reservationId": 3,
  "rating": 5,
  "content": "맛있어요 강추함"
}
