### sign-up-controller - customer
POST http://localhost:8085/signup/customer
Content-Type: application/json

{
  "name": "suh-customer",
  "email": "chan4760@naver.com",
  "password": "string",
  "phone": "string",
  "birth": "2023-12-29"
}


### sign-up-controller - partner
POST http://localhost:8085/signup/partner
Content-Type: application/json

{
  "name": "suh-partner",
  "email": "chan4760@gmail.com",
  "password": "string",
  "phone": "string",
  "birth": "2023-12-29"
}


######################################################
/

### sign-in-controller - customer
POST http://localhost:8085/signin/customer
Content-Type: application/json

{
  "email": "chan4760@naver.com",
  "password": "string"
}

### eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTI5OTE5LCJleHAiOjE3MDQyMTYzMTl9.wMMELGcr1levieDpBM0E4s7Mv66n35THCu5bvj_IYZ4


### sign-in-controller - partner
POST http://localhost:8085/signin/partner
Content-Type: application/json

{
  "email": "chan4760@gmail.com",
  "password": "string"
}

###eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTE4NzM4LCJleHAiOjE3MDQyMDUxMzh9.HSAcOZPSLzONzC3rHS2Z_I7N42iK0MmWMG_1QZLZivk


######################################################
/

### store-contorller -/store/partner/edit/{storeId}
PUT http://localhost:8085/store/partner/edit/1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTE4NzM4LCJleHAiOjE3MDQyMDUxMzh9.HSAcOZPSLzONzC3rHS2Z_I7N42iK0MmWMG_1QZLZivk

{
  "name": "Store12",
  "location": "string",
  "description": "string",
  "openingTime": "01:00:00",
  "closingTime": "23:50:00",
  "isAvaliableReservation": true,
  "maxReservationPeople": 4
}

### store-contorller -/store/partner/create
POST http://localhost:8085/store/partner/create
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTE4NzM4LCJleHAiOjE3MDQyMDUxMzh9.HSAcOZPSLzONzC3rHS2Z_I7N42iK0MmWMG_1QZLZivk

{
  "name": "Store1",
  "location": "string",
  "description": "string",
  "openingTime": "00:01:00",
  "closingTime": "23:50:00",
  "isAvaliableReservation": true,
  "maxReservationPeople": 4
}



### store-contorller -/store/search
GET http://localhost:8085/store/search?keyWord=Store
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTE4NzM4LCJleHAiOjE3MDQyMDUxMzh9.HSAcOZPSLzONzC3rHS2Z_I7N42iK0MmWMG_1QZLZivk

### store-contorller -/store/partner/stores-info
GET http://localhost:8085/store/partner/stores-info
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTE4NzM4LCJleHAiOjE3MDQyMDUxMzh9.HSAcOZPSLzONzC3rHS2Z_I7N42iK0MmWMG_1QZLZivk

### store-contorller -/store/partner/delete/{storeId}
DELETE http://localhost:8085/store/partner/delete/2
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTE4NzM4LCJleHAiOjE3MDQyMDUxMzh9.HSAcOZPSLzONzC3rHS2Z_I7N42iK0MmWMG_1QZLZivk

######################################################
/

### reservation-controller - /reservation/customer/create
POST http://localhost:8085/reservation/customer/create
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTI5OTE5LCJleHAiOjE3MDQyMTYzMTl9.wMMELGcr1levieDpBM0E4s7Mv66n35THCu5bvj_IYZ4

{
  "storeName": "Store1",
  "reservationName": "chan",
  "reservationPhone": "00011000000",
  "reservationTime": "2024-01-02T01:50:00",
  "numberOfPerson": 2
}

### reservation-controller - /reservation/partner/store-reservation-info/{storeId}
GET http://localhost:8085/reservation/partner/store-reservation-info/1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTE4NzM4LCJleHAiOjE3MDQyMDUxMzh9.HSAcOZPSLzONzC3rHS2Z_I7N42iK0MmWMG_1QZLZivk

### reservation-controller - /reservation/customer/reservations-info
GET http://localhost:8085/reservation/customer/reservations-info
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTI5OTE5LCJleHAiOjE3MDQyMTYzMTl9.wMMELGcr1levieDpBM0E4s7Mv66n35THCu5bvj_IYZ4

### reservation-controller - /reservation/kiosk/visit-confirm/{reservationCode}
POST http://localhost:8085/reservation/kiosk/visit-confirm/f03bac87f11b40c28bdf3abe2852b464
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTI5OTE5LCJleHAiOjE3MDQyMTYzMTl9.wMMELGcr1levieDpBM0E4s7Mv66n35THCu5bvj_IYZ4

### reservation-controller - /reservation/partner/confirm/{reservationId}
POST http://localhost:8085/reservation/partner/confirm/1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBnbWFpbC5jb20iLCJqdGkiOiIxIiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA0MTE4NzM4LCJleHAiOjE3MDQyMDUxMzh9.HSAcOZPSLzONzC3rHS2Z_I7N42iK0MmWMG_1QZLZivk
